"""Sirius models.

Revision ID: 31a4efaaa779
Revises: None
Create Date: 2015-01-07 17:33:02.404123

"""

# revision identifiers, used by Alembic.
revision = '31a4efaaa779'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('bridge_address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'bridge_address')
    )
    op.create_table('device_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('device_address', sa.String(), nullable=True),
    sa.Column('entry', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('printer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('device_address', sa.String(), nullable=True),
    sa.Column('hardware_xor', sa.String(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('used_claim_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitter_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('screen_name', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_name'),
    sa.UniqueConstraint('token')
    )
    op.create_table('claim_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('by', sa.Integer(), nullable=True),
    sa.Column('hardware_xor', sa.String(), nullable=True),
    sa.Column('claim_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['by'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_code')
    op.drop_table('twitter_oauth')
    op.drop_table('printer')
    op.drop_table('device_log')
    op.drop_table('bridge')
    op.drop_table('user')
    ### end Alembic commands ###
