"""Sirius models.

Revision ID: 4a0698610fcd
Revises: None
Create Date: 2015-01-15 11:27:22.373207

"""

# revision identifiers, used by Alembic.
revision = '4a0698610fcd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('bridge_address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'bridge_address')
    )
    op.create_table('device_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('device_address', sa.String(), nullable=True),
    sa.Column('entry', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitter_o_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('screen_name', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_name'),
    sa.UniqueConstraint('token')
    )
    op.create_table('claim_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('by_id', sa.Integer(), nullable=True),
    sa.Column('hardware_xor', sa.Integer(), nullable=True),
    sa.Column('claim_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('printer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('device_address', sa.String(), nullable=True),
    sa.Column('hardware_xor', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('used_claim_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('printer')
    op.drop_table('claim_code')
    op.drop_table('twitter_o_auth')
    op.drop_table('user')
    op.drop_table('device_log')
    op.drop_table('bridge')
    ### end Alembic commands ###
