"""empty message

Revision ID: 571ce49cc27
Revises: None
Create Date: 2014-09-27 13:49:33.601801

"""

# revision identifiers, used by Alembic.
revision = '571ce49cc27'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridge_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('bridge_address', sa.String(), nullable=False),
    sa.Column('json_payload', sa.UnicodeText(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('return_code', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_address', sa.String(), nullable=False),
    sa.Column('binary_payload', sa.Text(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('deliver_at', sa.DateTime(), nullable=False),
    sa.Column('return_code', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('device_address', sa.String(), nullable=False),
    sa.Column('hardware_xor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('device_address')
    )
    op.create_table('pending_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_code', sa.String(), nullable=False),
    sa.Column('hardware_xor', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bridges',
    sa.Column('bridge_address', sa.String(), nullable=False),
    sa.Column('last_power_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bridge_address')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bridges')
    op.drop_table('pending_claims')
    op.drop_table('devices')
    op.drop_table('device_commands')
    op.drop_table('bridge_commands')
    ### end Alembic commands ###
