"""initial migration

Revision ID: 595254b6b6e9
Revises: None
Create Date: 2014-09-27 13:28:03.860084

"""

# revision identifiers, used by Alembic.
revision = '595254b6b6e9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
